#!/usr/bin/env python3
"""Display the measurements regenerated by render.sh from the repository test."""
import re
from pathlib import Path

text = (Path(__file__).resolve().parents[1] / "out/measured-numbers.txt").read_text()
base = int(re.search(r"baseline bytes (\d+)", text)[1])
rows = {name: (int(size), saved) for name, size, saved in re.findall(
    r"^(\w+)\s+(\d+) bytes\s+[\d.]+ of default\s+saves ([\d.]+)%", text, re.M)}
assert len(rows) == 6, "Expected all six measured payloads"
print("spider-agent / payload savings\n")
print("Recorded product page fixture. Response bytes, not live spend.\n")
print(f"{'Requested':<22}{'Bytes':>10}{'Saved':>12}")
print("-" * 44)
print(f"{'Default':<22}{base:>10,}{'':>12}")
for name in ("fields", "metadata", "links", "text", "markdown", "html"):
    size, saved = rows[name]
    print(f"{name:<22}{size:>10,}{saved + '%':>12}")
print("\nSource: thrift_budget::measured_numbers")
print(f"Fields return {rows['fields'][0]} bytes. The page body stays off the wire.")

# Let render.sh check the scene without the tape typing on screen.
(Path(__file__).resolve().parents[1] / "out/payload-savings.exit").write_text("0\n")
